### ISSUE TITLE
How to access ref to call clear

### ISSUE THREAD

**Issue by iamnives** [mmw/react-password-strength#46]
Hi, this is me being a noob but how do i call the clear function?

**Comment by mmw** [comment]
You can call it on the ref of the component. In `/example` we call `this.refs.passComponent.clear()` (with the component defined like this: `<ReactPasswordStrength ref="passComponent">`)

You can see the whole example [here](https://github.com/mmw/react-password-strength/blob/master/example/index.js#L19). Hope that helps, closing as I believe this is resolved. Let me know if you still have trouble.

**Comment by iamnives** [comment]
Yep thats it!

**Comment by nwhitmont** [comment]
@mmw The linked example page is showing 404 not found at https://github.com/mmw/react-password-strength/blob/master/example/index.js#L19

Could you add the usage example to the README?

**Comment by mmw** [comment]
@nwhitmont Ah sorry, I have moved the example to a separate repo since commenting on this issue. I believe I was linking to [this line](https://github.com/mmw/react-password-strength-example/blob/master/src/App.js#L10).

The link to the entire example exists [here](https://github.com/mmw/react-password-strength#run-the-example-locally)

**Comment by nwhitmont** [comment]
@mmw Thank you!
